### ISSUE TITLE
Build a "getting started" page

### ISSUE THREAD

**Issue by AlinaWithAFace** [AlinaWithAFace/ProjectNorthStar#12]
Probably something as the default landing page, just a hey-welccome-here's-where-everything's-at-here's-your-first-steps sort of thing

**Comment by BryanChrisBrown** [comment]
https://project-north-star.gitbook.io/project-north-star/

We can probably improve this page a bit, but I believe it covers the original issue

**Comment by AlinaWithAFace** [comment]
Yeah, it'll work for now
